/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ApiTokenStatus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class ApiTokenStatus {
  @JsonProperty("expiresInMillis")
  private Long expiresInMillis = null;

  @JsonProperty("remainingCalls")
  private Long remainingCalls = null;

  @JsonProperty("resetsInMillis")
  private Long resetsInMillis = null;

  @JsonProperty("token")
  private String token = null;

  @JsonProperty("totalRequests")
  private Long totalRequests = null;

  @JsonProperty("valid")
  private Boolean valid = null;

  public ApiTokenStatus expiresInMillis(Long expiresInMillis) {
    this.expiresInMillis = expiresInMillis;
    return this;
  }

   /**
   * Get expiresInMillis
   * @return expiresInMillis
  **/
  @ApiModelProperty(value = "")
  public Long getExpiresInMillis() {
    return expiresInMillis;
  }

  public void setExpiresInMillis(Long expiresInMillis) {
    this.expiresInMillis = expiresInMillis;
  }

  public ApiTokenStatus remainingCalls(Long remainingCalls) {
    this.remainingCalls = remainingCalls;
    return this;
  }

   /**
   * Get remainingCalls
   * @return remainingCalls
  **/
  @ApiModelProperty(value = "")
  public Long getRemainingCalls() {
    return remainingCalls;
  }

  public void setRemainingCalls(Long remainingCalls) {
    this.remainingCalls = remainingCalls;
  }

  public ApiTokenStatus resetsInMillis(Long resetsInMillis) {
    this.resetsInMillis = resetsInMillis;
    return this;
  }

   /**
   * Get resetsInMillis
   * @return resetsInMillis
  **/
  @ApiModelProperty(value = "")
  public Long getResetsInMillis() {
    return resetsInMillis;
  }

  public void setResetsInMillis(Long resetsInMillis) {
    this.resetsInMillis = resetsInMillis;
  }

  public ApiTokenStatus token(String token) {
    this.token = token;
    return this;
  }

   /**
   * Get token
   * @return token
  **/
  @ApiModelProperty(value = "")
  public String getToken() {
    return token;
  }

  public void setToken(String token) {
    this.token = token;
  }

  public ApiTokenStatus totalRequests(Long totalRequests) {
    this.totalRequests = totalRequests;
    return this;
  }

   /**
   * Get totalRequests
   * @return totalRequests
  **/
  @ApiModelProperty(value = "")
  public Long getTotalRequests() {
    return totalRequests;
  }

  public void setTotalRequests(Long totalRequests) {
    this.totalRequests = totalRequests;
  }

  public ApiTokenStatus valid(Boolean valid) {
    this.valid = valid;
    return this;
  }

   /**
   * Get valid
   * @return valid
  **/
  @ApiModelProperty(value = "")
  public Boolean isValid() {
    return valid;
  }

  public void setValid(Boolean valid) {
    this.valid = valid;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiTokenStatus apiTokenStatus = (ApiTokenStatus) o;
    return Objects.equals(this.expiresInMillis, apiTokenStatus.expiresInMillis) &&
        Objects.equals(this.remainingCalls, apiTokenStatus.remainingCalls) &&
        Objects.equals(this.resetsInMillis, apiTokenStatus.resetsInMillis) &&
        Objects.equals(this.token, apiTokenStatus.token) &&
        Objects.equals(this.totalRequests, apiTokenStatus.totalRequests) &&
        Objects.equals(this.valid, apiTokenStatus.valid);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expiresInMillis, remainingCalls, resetsInMillis, token, totalRequests, valid);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiTokenStatus {\n");
    
    sb.append("    expiresInMillis: ").append(toIndentedString(expiresInMillis)).append("\n");
    sb.append("    remainingCalls: ").append(toIndentedString(remainingCalls)).append("\n");
    sb.append("    resetsInMillis: ").append(toIndentedString(resetsInMillis)).append("\n");
    sb.append("    token: ").append(toIndentedString(token)).append("\n");
    sb.append("    totalRequests: ").append(toIndentedString(totalRequests)).append("\n");
    sb.append("    valid: ").append(toIndentedString(valid)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

