/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * Bigram
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class Bigram {
  @JsonProperty("count")
  private Long count = null;

  @JsonProperty("gram1")
  private String gram1 = null;

  @JsonProperty("gram2")
  private String gram2 = null;

  @JsonProperty("mi")
  private Double mi = null;

  @JsonProperty("wlmi")
  private Double wlmi = null;

  public Bigram count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public Bigram gram1(String gram1) {
    this.gram1 = gram1;
    return this;
  }

   /**
   * Get gram1
   * @return gram1
  **/
  @ApiModelProperty(value = "")
  public String getGram1() {
    return gram1;
  }

  public void setGram1(String gram1) {
    this.gram1 = gram1;
  }

  public Bigram gram2(String gram2) {
    this.gram2 = gram2;
    return this;
  }

   /**
   * Get gram2
   * @return gram2
  **/
  @ApiModelProperty(value = "")
  public String getGram2() {
    return gram2;
  }

  public void setGram2(String gram2) {
    this.gram2 = gram2;
  }

  public Bigram mi(Double mi) {
    this.mi = mi;
    return this;
  }

   /**
   * Get mi
   * @return mi
  **/
  @ApiModelProperty(value = "")
  public Double getMi() {
    return mi;
  }

  public void setMi(Double mi) {
    this.mi = mi;
  }

  public Bigram wlmi(Double wlmi) {
    this.wlmi = wlmi;
    return this;
  }

   /**
   * Get wlmi
   * @return wlmi
  **/
  @ApiModelProperty(value = "")
  public Double getWlmi() {
    return wlmi;
  }

  public void setWlmi(Double wlmi) {
    this.wlmi = wlmi;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Bigram bigram = (Bigram) o;
    return Objects.equals(this.count, bigram.count) &&
        Objects.equals(this.gram1, bigram.gram1) &&
        Objects.equals(this.gram2, bigram.gram2) &&
        Objects.equals(this.mi, bigram.mi) &&
        Objects.equals(this.wlmi, bigram.wlmi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, gram1, gram2, mi, wlmi);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bigram {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    gram1: ").append(toIndentedString(gram1)).append("\n");
    sb.append("    gram2: ").append(toIndentedString(gram2)).append("\n");
    sb.append("    mi: ").append(toIndentedString(mi)).append("\n");
    sb.append("    wlmi: ").append(toIndentedString(wlmi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

