/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * ExampleSearchResults
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class ExampleSearchResults {
  @JsonProperty("examples")
  private List<Object> examples = null;

  @JsonProperty("facets")
  private List<Object> facets = null;

  public ExampleSearchResults examples(List<Object> examples) {
    this.examples = examples;
    return this;
  }

  public ExampleSearchResults addExamplesItem(Object examplesItem) {
    if (this.examples == null) {
      this.examples = new ArrayList<Object>();
    }
    this.examples.add(examplesItem);
    return this;
  }

   /**
   * Get examples
   * @return examples
  **/
  @ApiModelProperty(value = "")
  public List<Object> getExamples() {
    return examples;
  }

  public void setExamples(List<Object> examples) {
    this.examples = examples;
  }

  public ExampleSearchResults facets(List<Object> facets) {
    this.facets = facets;
    return this;
  }

  public ExampleSearchResults addFacetsItem(Object facetsItem) {
    if (this.facets == null) {
      this.facets = new ArrayList<Object>();
    }
    this.facets.add(facetsItem);
    return this;
  }

   /**
   * Get facets
   * @return facets
  **/
  @ApiModelProperty(value = "")
  public List<Object> getFacets() {
    return facets;
  }

  public void setFacets(List<Object> facets) {
    this.facets = facets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExampleSearchResults exampleSearchResults = (ExampleSearchResults) o;
    return Objects.equals(this.examples, exampleSearchResults.examples) &&
        Objects.equals(this.facets, exampleSearchResults.facets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(examples, facets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExampleSearchResults {\n");
    
    sb.append("    examples: ").append(toIndentedString(examples)).append("\n");
    sb.append("    facets: ").append(toIndentedString(facets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

