/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Facet
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class Facet {
  @JsonProperty("facetValues")
  private List<Object> facetValues = null;

  @JsonProperty("name")
  private String name = null;

  public Facet facetValues(List<Object> facetValues) {
    this.facetValues = facetValues;
    return this;
  }

  public Facet addFacetValuesItem(Object facetValuesItem) {
    if (this.facetValues == null) {
      this.facetValues = new ArrayList<Object>();
    }
    this.facetValues.add(facetValuesItem);
    return this;
  }

   /**
   * Get facetValues
   * @return facetValues
  **/
  @ApiModelProperty(value = "")
  public List<Object> getFacetValues() {
    return facetValues;
  }

  public void setFacetValues(List<Object> facetValues) {
    this.facetValues = facetValues;
  }

  public Facet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Facet facet = (Facet) o;
    return Objects.equals(this.facetValues, facet.facetValues) &&
        Objects.equals(this.name, facet.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facetValues, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Facet {\n");
    
    sb.append("    facetValues: ").append(toIndentedString(facetValues)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

