/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * FrequencySummary
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class FrequencySummary {
  @JsonProperty("frequency")
  private List<Object> frequency = null;

  @JsonProperty("frequencyString")
  private String frequencyString = null;

  @JsonProperty("totalCount")
  private Long totalCount = null;

  @JsonProperty("unknownYearCount")
  private Integer unknownYearCount = null;

  @JsonProperty("word")
  private String word = null;

  public FrequencySummary frequency(List<Object> frequency) {
    this.frequency = frequency;
    return this;
  }

  public FrequencySummary addFrequencyItem(Object frequencyItem) {
    if (this.frequency == null) {
      this.frequency = new ArrayList<Object>();
    }
    this.frequency.add(frequencyItem);
    return this;
  }

   /**
   * Get frequency
   * @return frequency
  **/
  @ApiModelProperty(value = "")
  public List<Object> getFrequency() {
    return frequency;
  }

  public void setFrequency(List<Object> frequency) {
    this.frequency = frequency;
  }

  public FrequencySummary frequencyString(String frequencyString) {
    this.frequencyString = frequencyString;
    return this;
  }

   /**
   * Get frequencyString
   * @return frequencyString
  **/
  @ApiModelProperty(value = "")
  public String getFrequencyString() {
    return frequencyString;
  }

  public void setFrequencyString(String frequencyString) {
    this.frequencyString = frequencyString;
  }

  public FrequencySummary totalCount(Long totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  @ApiModelProperty(value = "")
  public Long getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Long totalCount) {
    this.totalCount = totalCount;
  }

  public FrequencySummary unknownYearCount(Integer unknownYearCount) {
    this.unknownYearCount = unknownYearCount;
    return this;
  }

   /**
   * Get unknownYearCount
   * @return unknownYearCount
  **/
  @ApiModelProperty(value = "")
  public Integer getUnknownYearCount() {
    return unknownYearCount;
  }

  public void setUnknownYearCount(Integer unknownYearCount) {
    this.unknownYearCount = unknownYearCount;
  }

  public FrequencySummary word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Get word
   * @return word
  **/
  @ApiModelProperty(value = "")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FrequencySummary frequencySummary = (FrequencySummary) o;
    return Objects.equals(this.frequency, frequencySummary.frequency) &&
        Objects.equals(this.frequencyString, frequencySummary.frequencyString) &&
        Objects.equals(this.totalCount, frequencySummary.totalCount) &&
        Objects.equals(this.unknownYearCount, frequencySummary.unknownYearCount) &&
        Objects.equals(this.word, frequencySummary.word);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frequency, frequencyString, totalCount, unknownYearCount, word);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FrequencySummary {\n");
    
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    frequencyString: ").append(toIndentedString(frequencyString)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("    unknownYearCount: ").append(toIndentedString(unknownYearCount)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

