/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Related
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class Related {
  @JsonProperty("gram")
  private String gram = null;

  @JsonProperty("label1")
  private String label1 = null;

  @JsonProperty("label2")
  private String label2 = null;

  @JsonProperty("label3")
  private String label3 = null;

  @JsonProperty("label4")
  private String label4 = null;

  @JsonProperty("relationshipType")
  private String relationshipType = null;

  @JsonProperty("words")
  private List<String> words = null;

  public Related gram(String gram) {
    this.gram = gram;
    return this;
  }

   /**
   * Get gram
   * @return gram
  **/
  @ApiModelProperty(value = "")
  public String getGram() {
    return gram;
  }

  public void setGram(String gram) {
    this.gram = gram;
  }

  public Related label1(String label1) {
    this.label1 = label1;
    return this;
  }

   /**
   * Get label1
   * @return label1
  **/
  @ApiModelProperty(value = "")
  public String getLabel1() {
    return label1;
  }

  public void setLabel1(String label1) {
    this.label1 = label1;
  }

  public Related label2(String label2) {
    this.label2 = label2;
    return this;
  }

   /**
   * Get label2
   * @return label2
  **/
  @ApiModelProperty(value = "")
  public String getLabel2() {
    return label2;
  }

  public void setLabel2(String label2) {
    this.label2 = label2;
  }

  public Related label3(String label3) {
    this.label3 = label3;
    return this;
  }

   /**
   * Get label3
   * @return label3
  **/
  @ApiModelProperty(value = "")
  public String getLabel3() {
    return label3;
  }

  public void setLabel3(String label3) {
    this.label3 = label3;
  }

  public Related label4(String label4) {
    this.label4 = label4;
    return this;
  }

   /**
   * Get label4
   * @return label4
  **/
  @ApiModelProperty(value = "")
  public String getLabel4() {
    return label4;
  }

  public void setLabel4(String label4) {
    this.label4 = label4;
  }

  public Related relationshipType(String relationshipType) {
    this.relationshipType = relationshipType;
    return this;
  }

   /**
   * Get relationshipType
   * @return relationshipType
  **/
  @ApiModelProperty(value = "")
  public String getRelationshipType() {
    return relationshipType;
  }

  public void setRelationshipType(String relationshipType) {
    this.relationshipType = relationshipType;
  }

  public Related words(List<String> words) {
    this.words = words;
    return this;
  }

  public Related addWordsItem(String wordsItem) {
    if (this.words == null) {
      this.words = new ArrayList<String>();
    }
    this.words.add(wordsItem);
    return this;
  }

   /**
   * Get words
   * @return words
  **/
  @ApiModelProperty(value = "")
  public List<String> getWords() {
    return words;
  }

  public void setWords(List<String> words) {
    this.words = words;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Related related = (Related) o;
    return Objects.equals(this.gram, related.gram) &&
        Objects.equals(this.label1, related.label1) &&
        Objects.equals(this.label2, related.label2) &&
        Objects.equals(this.label3, related.label3) &&
        Objects.equals(this.label4, related.label4) &&
        Objects.equals(this.relationshipType, related.relationshipType) &&
        Objects.equals(this.words, related.words);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gram, label1, label2, label3, label4, relationshipType, words);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Related {\n");
    
    sb.append("    gram: ").append(toIndentedString(gram)).append("\n");
    sb.append("    label1: ").append(toIndentedString(label1)).append("\n");
    sb.append("    label2: ").append(toIndentedString(label2)).append("\n");
    sb.append("    label3: ").append(toIndentedString(label3)).append("\n");
    sb.append("    label4: ").append(toIndentedString(label4)).append("\n");
    sb.append("    relationshipType: ").append(toIndentedString(relationshipType)).append("\n");
    sb.append("    words: ").append(toIndentedString(words)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

