/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * ScoredWord
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class ScoredWord {
  @JsonProperty("baseWordScore")
  private Double baseWordScore = null;

  @JsonProperty("docTermCount")
  private Integer docTermCount = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("lemma")
  private String lemma = null;

  @JsonProperty("partOfSpeech")
  private String partOfSpeech = null;

  @JsonProperty("position")
  private Integer position = null;

  @JsonProperty("score")
  private Float score = null;

  @JsonProperty("sentenceId")
  private Long sentenceId = null;

  @JsonProperty("stopword")
  private Boolean stopword = null;

  @JsonProperty("word")
  private String word = null;

  @JsonProperty("wordType")
  private String wordType = null;

  public ScoredWord baseWordScore(Double baseWordScore) {
    this.baseWordScore = baseWordScore;
    return this;
  }

   /**
   * Get baseWordScore
   * @return baseWordScore
  **/
  @ApiModelProperty(value = "")
  public Double getBaseWordScore() {
    return baseWordScore;
  }

  public void setBaseWordScore(Double baseWordScore) {
    this.baseWordScore = baseWordScore;
  }

  public ScoredWord docTermCount(Integer docTermCount) {
    this.docTermCount = docTermCount;
    return this;
  }

   /**
   * Get docTermCount
   * @return docTermCount
  **/
  @ApiModelProperty(value = "")
  public Integer getDocTermCount() {
    return docTermCount;
  }

  public void setDocTermCount(Integer docTermCount) {
    this.docTermCount = docTermCount;
  }

  public ScoredWord id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public ScoredWord lemma(String lemma) {
    this.lemma = lemma;
    return this;
  }

   /**
   * Get lemma
   * @return lemma
  **/
  @ApiModelProperty(value = "")
  public String getLemma() {
    return lemma;
  }

  public void setLemma(String lemma) {
    this.lemma = lemma;
  }

  public ScoredWord partOfSpeech(String partOfSpeech) {
    this.partOfSpeech = partOfSpeech;
    return this;
  }

   /**
   * Get partOfSpeech
   * @return partOfSpeech
  **/
  @ApiModelProperty(value = "")
  public String getPartOfSpeech() {
    return partOfSpeech;
  }

  public void setPartOfSpeech(String partOfSpeech) {
    this.partOfSpeech = partOfSpeech;
  }

  public ScoredWord position(Integer position) {
    this.position = position;
    return this;
  }

   /**
   * Get position
   * @return position
  **/
  @ApiModelProperty(value = "")
  public Integer getPosition() {
    return position;
  }

  public void setPosition(Integer position) {
    this.position = position;
  }

  public ScoredWord score(Float score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(value = "")
  public Float getScore() {
    return score;
  }

  public void setScore(Float score) {
    this.score = score;
  }

  public ScoredWord sentenceId(Long sentenceId) {
    this.sentenceId = sentenceId;
    return this;
  }

   /**
   * Get sentenceId
   * @return sentenceId
  **/
  @ApiModelProperty(value = "")
  public Long getSentenceId() {
    return sentenceId;
  }

  public void setSentenceId(Long sentenceId) {
    this.sentenceId = sentenceId;
  }

  public ScoredWord stopword(Boolean stopword) {
    this.stopword = stopword;
    return this;
  }

   /**
   * Get stopword
   * @return stopword
  **/
  @ApiModelProperty(value = "")
  public Boolean isStopword() {
    return stopword;
  }

  public void setStopword(Boolean stopword) {
    this.stopword = stopword;
  }

  public ScoredWord word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Get word
   * @return word
  **/
  @ApiModelProperty(value = "")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }

  public ScoredWord wordType(String wordType) {
    this.wordType = wordType;
    return this;
  }

   /**
   * Get wordType
   * @return wordType
  **/
  @ApiModelProperty(value = "")
  public String getWordType() {
    return wordType;
  }

  public void setWordType(String wordType) {
    this.wordType = wordType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScoredWord scoredWord = (ScoredWord) o;
    return Objects.equals(this.baseWordScore, scoredWord.baseWordScore) &&
        Objects.equals(this.docTermCount, scoredWord.docTermCount) &&
        Objects.equals(this.id, scoredWord.id) &&
        Objects.equals(this.lemma, scoredWord.lemma) &&
        Objects.equals(this.partOfSpeech, scoredWord.partOfSpeech) &&
        Objects.equals(this.position, scoredWord.position) &&
        Objects.equals(this.score, scoredWord.score) &&
        Objects.equals(this.sentenceId, scoredWord.sentenceId) &&
        Objects.equals(this.stopword, scoredWord.stopword) &&
        Objects.equals(this.word, scoredWord.word) &&
        Objects.equals(this.wordType, scoredWord.wordType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(baseWordScore, docTermCount, id, lemma, partOfSpeech, position, score, sentenceId, stopword, word, wordType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScoredWord {\n");
    
    sb.append("    baseWordScore: ").append(toIndentedString(baseWordScore)).append("\n");
    sb.append("    docTermCount: ").append(toIndentedString(docTermCount)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lemma: ").append(toIndentedString(lemma)).append("\n");
    sb.append("    partOfSpeech: ").append(toIndentedString(partOfSpeech)).append("\n");
    sb.append("    position: ").append(toIndentedString(position)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    sentenceId: ").append(toIndentedString(sentenceId)).append("\n");
    sb.append("    stopword: ").append(toIndentedString(stopword)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("    wordType: ").append(toIndentedString(wordType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

