/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Sentence
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class Sentence {
  @JsonProperty("display")
  private String display = null;

  @JsonProperty("documentMetadataId")
  private Long documentMetadataId = null;

  @JsonProperty("hasScoredWords")
  private Boolean hasScoredWords = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("rating")
  private Integer rating = null;

  @JsonProperty("scoredWords")
  private List<Object> scoredWords = null;

  public Sentence display(String display) {
    this.display = display;
    return this;
  }

   /**
   * Get display
   * @return display
  **/
  @ApiModelProperty(value = "")
  public String getDisplay() {
    return display;
  }

  public void setDisplay(String display) {
    this.display = display;
  }

  public Sentence documentMetadataId(Long documentMetadataId) {
    this.documentMetadataId = documentMetadataId;
    return this;
  }

   /**
   * Get documentMetadataId
   * @return documentMetadataId
  **/
  @ApiModelProperty(value = "")
  public Long getDocumentMetadataId() {
    return documentMetadataId;
  }

  public void setDocumentMetadataId(Long documentMetadataId) {
    this.documentMetadataId = documentMetadataId;
  }

  public Sentence hasScoredWords(Boolean hasScoredWords) {
    this.hasScoredWords = hasScoredWords;
    return this;
  }

   /**
   * Get hasScoredWords
   * @return hasScoredWords
  **/
  @ApiModelProperty(value = "")
  public Boolean isHasScoredWords() {
    return hasScoredWords;
  }

  public void setHasScoredWords(Boolean hasScoredWords) {
    this.hasScoredWords = hasScoredWords;
  }

  public Sentence id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Sentence rating(Integer rating) {
    this.rating = rating;
    return this;
  }

   /**
   * Get rating
   * @return rating
  **/
  @ApiModelProperty(value = "")
  public Integer getRating() {
    return rating;
  }

  public void setRating(Integer rating) {
    this.rating = rating;
  }

  public Sentence scoredWords(List<Object> scoredWords) {
    this.scoredWords = scoredWords;
    return this;
  }

  public Sentence addScoredWordsItem(Object scoredWordsItem) {
    if (this.scoredWords == null) {
      this.scoredWords = new ArrayList<Object>();
    }
    this.scoredWords.add(scoredWordsItem);
    return this;
  }

   /**
   * Get scoredWords
   * @return scoredWords
  **/
  @ApiModelProperty(value = "")
  public List<Object> getScoredWords() {
    return scoredWords;
  }

  public void setScoredWords(List<Object> scoredWords) {
    this.scoredWords = scoredWords;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sentence sentence = (Sentence) o;
    return Objects.equals(this.display, sentence.display) &&
        Objects.equals(this.documentMetadataId, sentence.documentMetadataId) &&
        Objects.equals(this.hasScoredWords, sentence.hasScoredWords) &&
        Objects.equals(this.id, sentence.id) &&
        Objects.equals(this.rating, sentence.rating) &&
        Objects.equals(this.scoredWords, sentence.scoredWords);
  }

  @Override
  public int hashCode() {
    return Objects.hash(display, documentMetadataId, hasScoredWords, id, rating, scoredWords);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sentence {\n");
    
    sb.append("    display: ").append(toIndentedString(display)).append("\n");
    sb.append("    documentMetadataId: ").append(toIndentedString(documentMetadataId)).append("\n");
    sb.append("    hasScoredWords: ").append(toIndentedString(hasScoredWords)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    rating: ").append(toIndentedString(rating)).append("\n");
    sb.append("    scoredWords: ").append(toIndentedString(scoredWords)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

