/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * WordSearchResult
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class WordSearchResult {
  @JsonProperty("count")
  private Long count = null;

  @JsonProperty("lexicality")
  private Double lexicality = null;

  @JsonProperty("word")
  private String word = null;

  public WordSearchResult count(Long count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  @ApiModelProperty(value = "")
  public Long getCount() {
    return count;
  }

  public void setCount(Long count) {
    this.count = count;
  }

  public WordSearchResult lexicality(Double lexicality) {
    this.lexicality = lexicality;
    return this;
  }

   /**
   * Get lexicality
   * @return lexicality
  **/
  @ApiModelProperty(value = "")
  public Double getLexicality() {
    return lexicality;
  }

  public void setLexicality(Double lexicality) {
    this.lexicality = lexicality;
  }

  public WordSearchResult word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Get word
   * @return word
  **/
  @ApiModelProperty(value = "")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WordSearchResult wordSearchResult = (WordSearchResult) o;
    return Objects.equals(this.count, wordSearchResult.count) &&
        Objects.equals(this.lexicality, wordSearchResult.lexicality) &&
        Objects.equals(this.word, wordSearchResult.word);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, lexicality, word);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WordSearchResult {\n");
    
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    lexicality: ").append(toIndentedString(lexicality)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

