/*
 * api.wordnik.com
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 4.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package edu.mills.cs180a.wordnik.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.threeten.bp.OffsetDateTime;

/**
 * WordListWord
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-04-10T17:59:52.032-07:00")
public class WordListWord {
  @JsonProperty("createdAt")
  private OffsetDateTime createdAt = null;

  @JsonProperty("id")
  private Long id = null;

  @JsonProperty("numberCommentsOnWord")
  private Long numberCommentsOnWord = null;

  @JsonProperty("numberLists")
  private Long numberLists = null;

  @JsonProperty("userId")
  private Long userId = null;

  @JsonProperty("username")
  private String username = null;

  @JsonProperty("word")
  private String word = null;

  public WordListWord createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public WordListWord id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public WordListWord numberCommentsOnWord(Long numberCommentsOnWord) {
    this.numberCommentsOnWord = numberCommentsOnWord;
    return this;
  }

   /**
   * Get numberCommentsOnWord
   * @return numberCommentsOnWord
  **/
  @ApiModelProperty(value = "")
  public Long getNumberCommentsOnWord() {
    return numberCommentsOnWord;
  }

  public void setNumberCommentsOnWord(Long numberCommentsOnWord) {
    this.numberCommentsOnWord = numberCommentsOnWord;
  }

  public WordListWord numberLists(Long numberLists) {
    this.numberLists = numberLists;
    return this;
  }

   /**
   * Get numberLists
   * @return numberLists
  **/
  @ApiModelProperty(value = "")
  public Long getNumberLists() {
    return numberLists;
  }

  public void setNumberLists(Long numberLists) {
    this.numberLists = numberLists;
  }

  public WordListWord userId(Long userId) {
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(value = "")
  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public WordListWord username(String username) {
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @ApiModelProperty(value = "")
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public WordListWord word(String word) {
    this.word = word;
    return this;
  }

   /**
   * Get word
   * @return word
  **/
  @ApiModelProperty(value = "")
  public String getWord() {
    return word;
  }

  public void setWord(String word) {
    this.word = word;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WordListWord wordListWord = (WordListWord) o;
    return Objects.equals(this.createdAt, wordListWord.createdAt) &&
        Objects.equals(this.id, wordListWord.id) &&
        Objects.equals(this.numberCommentsOnWord, wordListWord.numberCommentsOnWord) &&
        Objects.equals(this.numberLists, wordListWord.numberLists) &&
        Objects.equals(this.userId, wordListWord.userId) &&
        Objects.equals(this.username, wordListWord.username) &&
        Objects.equals(this.word, wordListWord.word);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, id, numberCommentsOnWord, numberLists, userId, username, word);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WordListWord {\n");
    
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    numberCommentsOnWord: ").append(toIndentedString(numberCommentsOnWord)).append("\n");
    sb.append("    numberLists: ").append(toIndentedString(numberLists)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    word: ").append(toIndentedString(word)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

